import React from "react";
import { View, StyleSheet, ScrollView } from "react-native";
import { ThemedText } from "@/components/ThemedText";
import { ThemedView } from "@/components/ThemedView";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useHeaderHeight } from "@react-navigation/elements";
import { Colors, Spacing, BorderRadius, Typography } from "@/constants/theme";

export default function TermsOfServiceScreen() {
  const insets = useSafeAreaInsets();
  const headerHeight = useHeaderHeight();

  return (
    <ThemedView style={styles.container}>
      <ScrollView
        contentContainerStyle={[
          styles.scrollContent,
          {
            paddingTop: headerHeight + Spacing.lg,
            paddingBottom: insets.bottom + Spacing["2xl"],
          },
        ]}
        showsVerticalScrollIndicator={false}
      >
        <ThemedText style={styles.title}>Terms of Service</ThemedText>
        <ThemedText style={styles.lastUpdated}>
          Last Updated: January 2026
        </ThemedText>

        <View style={styles.section}>
          <ThemedText style={styles.sectionTitle}>
            1. Acceptance of Terms
          </ThemedText>
          <ThemedText style={styles.paragraph}>
            By accessing and using HiddenGem by The Relic Shop ("the App"), you
            accept and agree to be bound by the terms and provisions of this
            agreement. If you do not agree to these terms, please do not use the
            App.
          </ThemedText>
        </View>

        <View style={styles.section}>
          <ThemedText style={styles.sectionTitle}>
            2. Description of Service
          </ThemedText>
          <ThemedText style={styles.paragraph}>
            HiddenGem is an inventory management application designed for
            resellers. The App provides tools for scanning collectible items,
            AI-powered appraisals, and listing generation for marketplace
            platforms including WooCommerce and eBay.
          </ThemedText>
        </View>

        <View style={styles.section}>
          <ThemedText style={styles.sectionTitle}>
            3. User Responsibilities
          </ThemedText>
          <ThemedText style={styles.paragraph}>
            You are responsible for maintaining the confidentiality of your API
            keys and marketplace credentials. You agree to provide accurate
            information when using the App and to comply with all applicable
            laws regarding the sale of items through connected marketplaces.
          </ThemedText>
        </View>

        <View style={styles.section}>
          <ThemedText style={styles.sectionTitle}>
            4. API Keys and Third-Party Services
          </ThemedText>
          <ThemedText style={styles.paragraph}>
            The App requires you to provide your own API keys for AI services
            (such as Google Gemini) and marketplace credentials. You are
            responsible for any charges incurred through these third-party
            services. The App stores these credentials securely on your device.
          </ThemedText>
        </View>

        <View style={styles.section}>
          <ThemedText style={styles.sectionTitle}>
            5. AI-Generated Content
          </ThemedText>
          <ThemedText style={styles.paragraph}>
            Appraisals and listing descriptions generated by AI are provided for
            informational purposes only. We do not guarantee the accuracy of
            valuations or descriptions. You are responsible for reviewing and
            verifying all content before publishing to marketplaces.
          </ThemedText>
        </View>

        <View style={styles.section}>
          <ThemedText style={styles.sectionTitle}>
            6. Intellectual Property
          </ThemedText>
          <ThemedText style={styles.paragraph}>
            The App and its original content, features, and functionality are
            owned by The Relic Shop and are protected by international
            copyright, trademark, and other intellectual property laws.
          </ThemedText>
        </View>

        <View style={styles.section}>
          <ThemedText style={styles.sectionTitle}>
            7. Limitation of Liability
          </ThemedText>
          <ThemedText style={styles.paragraph}>
            The Relic Shop shall not be liable for any indirect, incidental,
            special, consequential, or punitive damages resulting from your use
            of the App, including but not limited to losses from marketplace
            transactions or inaccurate AI appraisals.
          </ThemedText>
        </View>

        <View style={styles.section}>
          <ThemedText style={styles.sectionTitle}>
            8. Changes to Terms
          </ThemedText>
          <ThemedText style={styles.paragraph}>
            We reserve the right to modify these terms at any time. We will
            notify users of any changes by updating the "Last Updated" date.
            Continued use of the App after changes constitutes acceptance of the
            new terms.
          </ThemedText>
        </View>

        <View style={styles.section}>
          <ThemedText style={styles.sectionTitle}>9. Contact Us</ThemedText>
          <ThemedText style={styles.paragraph}>
            If you have any questions about these Terms of Service, please
            contact us at support@therelicshop.com.
          </ThemedText>
        </View>
      </ScrollView>
    </ThemedView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.dark.backgroundRoot,
  },
  scrollContent: {
    paddingHorizontal: Spacing.lg,
  },
  title: {
    ...Typography.h2,
    color: Colors.dark.text,
    marginBottom: Spacing.sm,
  },
  lastUpdated: {
    ...Typography.caption,
    color: Colors.dark.textSecondary,
    marginBottom: Spacing["2xl"],
  },
  section: {
    marginBottom: Spacing.xl,
  },
  sectionTitle: {
    ...Typography.h4,
    color: Colors.dark.primary,
    marginBottom: Spacing.sm,
  },
  paragraph: {
    ...Typography.body,
    color: Colors.dark.textSecondary,
    lineHeight: 24,
  },
});
